const { PGlite } = require(process.argv[2] || '@electric-sql/pglite');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
 const db = new PGlite();
 await db.exec(`create role anon; create role authenticated;
 create schema auth; create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid$$;
 grant usage on schema auth to authenticated;
 insert into auth.users values ('11111111-1111-1111-1111-111111111111'),('22222222-2222-2222-2222-222222222222');`);
 await db.exec(fs.readFileSync(path.join(__dirname, '../supabase/migrations/20261008224118_investment_theses.sql'),'utf8'));
 await db.exec(`set role authenticated; set request.jwt.claim.sub='11111111-1111-1111-1111-111111111111';`);
 const row = `('11111111-1111-1111-1111-111111111111','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',1,'NVDA','bullish','Original reason','1–3 months')`;
 const insert = `insert into public.investment_thesis_versions(user_id,thesis_id,version,ticker,direction,reasoning,horizon) values ${row}`;
 await db.exec(insert);
 await db.exec(insert.replace(',1,',',2,').replace('Original reason','Updated reason'));
 const current = await db.query('select version,reasoning from investment_thesis_current');
 assert.deepEqual(current.rows,[{version:2,reasoning:'Updated reason'}]);
 assert.equal((await db.query('select * from investment_thesis_versions')).rows.length,2);
 await assert.rejects(db.exec(insert), /duplicate key/);
 await assert.rejects(db.exec(`update investment_thesis_versions set reasoning='Overwrite'`), /permission denied/);
 await assert.rejects(db.exec(`delete from investment_thesis_versions`), /permission denied/);
 await db.exec(`set request.jwt.claim.sub='22222222-2222-2222-2222-222222222222';`);
 assert.equal((await db.query('select * from investment_thesis_current')).rows.length,0);
 assert.equal((await db.query('select * from investment_thesis_versions')).rows.length,0);
 await assert.rejects(db.exec(insert), /row-level security/);
 await db.exec(`reset role; set role anon;`);
 await assert.rejects(db.query('select * from investment_thesis_current'), /permission denied/);
 await assert.rejects(db.query('select * from investment_thesis_versions'), /permission denied/);
 await db.close();
 console.log('PASS: migration applies; current view selects newest version; history is append-only; stale version conflicts; cross-user reads/inserts blocked; anonymous reads blocked.');
})().catch(e=>{console.error(e);process.exit(1)});
